name: Lint

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]

jobs:
  checks:
    if: "!contains(toJSON(github.event.commits.*.message), '[skip ci]')"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm ci

      - name: Linting
        run: npm run lint

      - name: Formatting
        run: npm run format
